version: '2'

services:
  master:
    image: devopsevd/oss-jmeter-master
    container_name: master
    tty: true
    networks:
      - jmeter-network
  slave:
    image: devopsevd/oss-jmeter-slave
    container_name: slave
    networks:
      - jmeter-network

networks:
  jmeter-network:
    driver: bridge
